// Generated by com.xlend.orm.tools.dbgen.DbGenerator.class at Thu Nov 27 11:32:33 EET 2014
// generated file: do not modify
package com.as.orm;

import com.as.orm.dbobject.DbObject;
import com.as.orm.dbobject.ForeignKeyViolationException;
import com.as.orm.dbobject.Triggers;
import java.sql.*;
import java.util.ArrayList;

public class Department extends DbObject  {
    private static Triggers activeTriggers = null;
    private Integer departmentId = null;
    private String departmentName = null;

    public Department(Connection connection) {
        super(connection, "department", "department_id");
        setColumnNames(new String[]{"department_id", "department_name"});
    }

    public Department(Connection connection, Integer departmentId, String departmentName) {
        super(connection, "department", "department_id");
        setNew(departmentId.intValue() <= 0);
//        if (departmentId.intValue() != 0) {
            this.departmentId = departmentId;
//        }
        this.departmentName = departmentName;
    }

    public DbObject loadOnId(int id) throws SQLException, ForeignKeyViolationException {
        Department department = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        String stmt = "SELECT department_id,department_name FROM department WHERE department_id=" + id;
        try {
            ps = getConnection().prepareStatement(stmt);
            rs = ps.executeQuery();
            if (rs.next()) {
                department = new Department(getConnection());
                department.setDepartmentId(new Integer(rs.getInt(1)));
                department.setDepartmentName(rs.getString(2));
                department.setNew(false);
            }
        } finally {
            try {
                if (rs != null) rs.close();
            } finally {
                if (ps != null) ps.close();
            }
        }
        return department;
    }

    protected void insert() throws SQLException, ForeignKeyViolationException {
         if (getTriggers() != null) {
             getTriggers().beforeInsert(this);
         }
         PreparedStatement ps = null;
         String stmt =
                "INSERT INTO department ("+(getDepartmentId().intValue()!=0?"department_id,":"")+"department_name) values("+(getDepartmentId().intValue()!=0?"?,":"")+"?)";
         try {
             ps = getConnection().prepareStatement(stmt);
             int n = 0;
             if (getDepartmentId().intValue()!=0) {
                 ps.setObject(++n, getDepartmentId());
             }
             ps.setObject(++n, getDepartmentName());
             ps.execute();
         } finally {
             if (ps != null) ps.close();
         }
         ResultSet rs = null;
         if (getDepartmentId().intValue()==0) {
             stmt = "SELECT max(department_id) FROM department";
             try {
                 ps = getConnection().prepareStatement(stmt);
                 rs = ps.executeQuery();
                 if (rs.next()) {
                     setDepartmentId(new Integer(rs.getInt(1)));
                 }
             } finally {
                 try {
                     if (rs != null) rs.close();
                 } finally {
                     if (ps != null) ps.close();
                 }
             }
         }
         setNew(false);
         setWasChanged(false);
         if (getTriggers() != null) {
             getTriggers().afterInsert(this);
         }
    }

    public void save() throws SQLException, ForeignKeyViolationException {
        if (isNew()) {
            insert();
        } else {
            if (getTriggers() != null) {
                getTriggers().beforeUpdate(this);
            }
            PreparedStatement ps = null;
            String stmt =
                    "UPDATE department " +
                    "SET department_name = ?" + 
                    " WHERE department_id = " + getDepartmentId();
            try {
                ps = getConnection().prepareStatement(stmt);
                ps.setObject(1, getDepartmentName());
                ps.execute();
            } finally {
                if (ps != null) ps.close();
            }
            setWasChanged(false);
            if (getTriggers() != null) {
                getTriggers().afterUpdate(this);
            }
        }
    }

    public void delete() throws SQLException, ForeignKeyViolationException {
        if (User.exists(getConnection(),"department_id = " + getDepartmentId())) {
            throw new ForeignKeyViolationException("Can't delete, foreign key violation: user_department_fk");
        }
        if (getTriggers() != null) {
            getTriggers().beforeDelete(this);
        }
        PreparedStatement ps = null;
        String stmt =
                "DELETE FROM department " +
                "WHERE department_id = " + getDepartmentId();
        try {
            ps = getConnection().prepareStatement(stmt);
            ps.execute();
        } finally {
            if (ps != null) ps.close();
        }
        setDepartmentId(new Integer(-getDepartmentId().intValue()));
        if (getTriggers() != null) {
            getTriggers().afterDelete(this);
        }
    }

    public boolean isDeleted() {
        return (getDepartmentId().intValue() < 0);
    }

    public static DbObject[] load(Connection con,String whereCondition,String orderCondition) throws SQLException {
        ArrayList lst = new ArrayList();
        PreparedStatement ps = null;
        ResultSet rs = null;
        String stmt = "SELECT department_id,department_name FROM department " +
                ((whereCondition != null && whereCondition.length() > 0) ?
                " WHERE " + whereCondition : "") +
                ((orderCondition != null && orderCondition.length() > 0) ?
                " ORDER BY " + orderCondition : "");
        try {
            ps = con.prepareStatement(stmt);
            rs = ps.executeQuery();
            while (rs.next()) {
                DbObject dbObj;
                lst.add(dbObj=new Department(con,new Integer(rs.getInt(1)),rs.getString(2)));
                dbObj.setNew(false);
            }
        } finally {
            try {
                if (rs != null) rs.close();
            } finally {
                if (ps != null) ps.close();
            }
        }
        Department[] objects = new Department[lst.size()];
        for (int i = 0; i < lst.size(); i++) {
            Department department = (Department) lst.get(i);
            objects[i] = department;
        }
        return objects;
    }

    public static boolean exists(Connection con, String whereCondition) throws SQLException {
        if (con == null) {
            return true;
        }
        boolean ok = false;
        PreparedStatement ps = null;
        ResultSet rs = null;
        String stmt = "SELECT department_id FROM department " +
                ((whereCondition != null && whereCondition.length() > 0) ?
                "WHERE " + whereCondition : "");
        try {
            ps = con.prepareStatement(stmt);
            rs = ps.executeQuery();
            ok = rs.next();
        } finally {
            try {
                if (rs != null) rs.close();
            } finally {
                if (ps != null) ps.close();
            }
        }
        return ok;
    }

    //public String toString() {
    //    return getDepartmentId() + getDelimiter();
    //}

    public Integer getPK_ID() {
        return departmentId;
    }

    public void setPK_ID(Integer id) throws ForeignKeyViolationException {
        boolean prevIsNew = isNew();
        setDepartmentId(id);
        setNew(prevIsNew);
    }

    public Integer getDepartmentId() {
        return departmentId;
    }

    public void setDepartmentId(Integer departmentId) throws ForeignKeyViolationException {
        setWasChanged(this.departmentId != null && this.departmentId != departmentId);
        this.departmentId = departmentId;
        setNew(departmentId.intValue() == 0);
    }

    public String getDepartmentName() {
        return departmentName;
    }

    public void setDepartmentName(String departmentName) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.departmentName != null && !this.departmentName.equals(departmentName));
        this.departmentName = departmentName;
    }
    public Object[] getAsRow() {
        Object[] columnValues = new Object[2];
        columnValues[0] = getDepartmentId();
        columnValues[1] = getDepartmentName();
        return columnValues;
    }

    public static void setTriggers(Triggers triggers) {
        activeTriggers = triggers;
    }

    public static Triggers getTriggers() {
        return activeTriggers;
    }

    //for SOAP exhange
    @Override
    public void fillFromString(String row) throws ForeignKeyViolationException, SQLException {
        String[] flds = splitStr(row, delimiter);
        try {
            setDepartmentId(Integer.parseInt(flds[0]));
        } catch(NumberFormatException ne) {
            setDepartmentId(null);
        }
        setDepartmentName(flds[1]);
    }
}
