// Generated by com.xlend.orm.tools.dbgen.DbGenerator.class at Wed Oct 29 17:58:28 EET 2014
// generated file: do not modify
package com.as.orm;

import com.as.orm.dbobject.DbObject;
import com.as.orm.dbobject.ForeignKeyViolationException;
import com.as.orm.dbobject.Triggers;
import java.sql.*;
import java.util.ArrayList;

public class Order extends DbObject implements IDocument {
    private static Triggers activeTriggers = null;
    private Integer orderId = null;
    private String location = null;
    private String contractor = null;
    private Integer customerId = null;
    private Integer contactId = null;
    private String rigTankEq = null;
    private Double discount = null;
    private Double taxProc = null;
    private Integer taxId = null;
    private Integer poTypeId = null;
    private String poNumber = null;
    private Date dateIn = null;
    private Date dateOut = null;
    private Object signature = null;
    private Timestamp updatedAt = null;
    private Timestamp createdAt = null;
    private Integer createdBy = null;

    public Order(Connection connection) {
        super(connection, "order", "order_id");
        setColumnNames(new String[]{"order_id", "location", "contractor", "customer_id", "contact_id", "rig_tank_eq", "discount", "tax_proc", "tax_id", "po_type_id", "po_number", "date_in", "date_out", "signature", "updated_at", "created_at", "created_by"});
    }

    public Order(Connection connection, Integer orderId, String location, String contractor, Integer customerId, Integer contactId, String rigTankEq, Double discount, Double taxProc, Integer taxId, Integer poTypeId, String poNumber, Date dateIn, Date dateOut, Object signature, Timestamp updatedAt, Timestamp createdAt, Integer createdBy) {
        super(connection, "order", "order_id");
        setNew(orderId.intValue() <= 0);
//        if (orderId.intValue() != 0) {
            this.orderId = orderId;
//        }
        this.location = location;
        this.contractor = contractor;
        this.customerId = customerId;
        this.contactId = contactId;
        this.rigTankEq = rigTankEq;
        this.discount = discount;
        this.taxProc = taxProc;
        this.taxId = taxId;
        this.poTypeId = poTypeId;
        this.poNumber = poNumber;
        this.dateIn = dateIn;
        this.dateOut = dateOut;
        this.signature = signature;
        this.updatedAt = updatedAt;
        this.createdAt = createdAt;
        this.createdBy = createdBy;
    }

    public DbObject loadOnId(int id) throws SQLException, ForeignKeyViolationException {
        Order order = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        String stmt = "SELECT order_id,location,contractor,customer_id,contact_id,rig_tank_eq,discount,tax_proc,tax_id,po_type_id,po_number,date_in,date_out,signature,updated_at,created_at,created_by FROM `order` WHERE order_id=" + id;
        try {
            ps = getConnection().prepareStatement(stmt);
            rs = ps.executeQuery();
            if (rs.next()) {
                order = new Order(getConnection());
                order.setOrderId(new Integer(rs.getInt(1)));
                order.setLocation(rs.getString(2));
                order.setContractor(rs.getString(3));
                order.setCustomerId(new Integer(rs.getInt(4)));
                order.setContactId(new Integer(rs.getInt(5)));
                order.setRigTankEq(rs.getString(6));
                order.setDiscount(rs.getDouble(7));
                order.setTaxProc(rs.getDouble(8));
                order.setTaxId(new Integer(rs.getInt(9)));
                order.setPoTypeId(new Integer(rs.getInt(10)));
                order.setPoNumber(rs.getString(11));
                order.setDateIn(rs.getDate(12));
                order.setDateOut(rs.getDate(13));
                order.setSignature(rs.getObject(14));
                order.setUpdatedAt(rs.getTimestamp(15));
                order.setCreatedAt(rs.getTimestamp(16));
                order.setCreatedBy(new Integer(rs.getInt(17)));
                order.setNew(false);
            }
        } finally {
            try {
                if (rs != null) rs.close();
            } finally {
                if (ps != null) ps.close();
            }
        }
        return order;
    }

    protected void insert() throws SQLException, ForeignKeyViolationException {
         if (getTriggers() != null) {
             getTriggers().beforeInsert(this);
         }
         PreparedStatement ps = null;
         String stmt =
                "INSERT INTO `order` ("+(getOrderId().intValue()!=0?"order_id,":"")+"location,contractor,customer_id,contact_id,rig_tank_eq,discount,tax_proc,tax_id,po_type_id,po_number,date_in,date_out,signature,updated_at,created_at,created_by) values("+(getOrderId().intValue()!=0?"?,":"")+"?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
         try {
             ps = getConnection().prepareStatement(stmt);
             int n = 0;
             if (getOrderId().intValue()!=0) {
                 ps.setObject(++n, getOrderId());
             }
             ps.setObject(++n, getLocation());
             ps.setObject(++n, getContractor());
             ps.setObject(++n, getCustomerId());
             ps.setObject(++n, getContactId());
             ps.setObject(++n, getRigTankEq());
             ps.setObject(++n, getDiscount());
             ps.setObject(++n, getTaxProc());
             ps.setObject(++n, getTaxId());
             ps.setObject(++n, getPoTypeId());
             ps.setObject(++n, getPoNumber());
             ps.setObject(++n, getDateIn());
             ps.setObject(++n, getDateOut());
             ps.setObject(++n, getSignature());
             ps.setObject(++n, getUpdatedAt());
             ps.setObject(++n, getCreatedAt());
             ps.setObject(++n, getCreatedBy());
             ps.execute();
         } finally {
             if (ps != null) ps.close();
         }
         ResultSet rs = null;
         if (getOrderId().intValue()==0) {
             stmt = "SELECT max(order_id) FROM `order`";
             try {
                 ps = getConnection().prepareStatement(stmt);
                 rs = ps.executeQuery();
                 if (rs.next()) {
                     setOrderId(new Integer(rs.getInt(1)));
                 }
             } finally {
                 try {
                     if (rs != null) rs.close();
                 } finally {
                     if (ps != null) ps.close();
                 }
             }
         }
         setNew(false);
         setWasChanged(false);
         if (getTriggers() != null) {
             getTriggers().afterInsert(this);
         }
    }

    public void save() throws SQLException, ForeignKeyViolationException {
        if (isNew()) {
            insert();
        } else {
            if (getTriggers() != null) {
                getTriggers().beforeUpdate(this);
            }
            PreparedStatement ps = null;
            String stmt =
                    "UPDATE `order` " +
                    "SET location = ?, contractor = ?, customer_id = ?, contact_id = ?, rig_tank_eq = ?, discount = ?, tax_proc = ?, tax_id = ?, po_type_id = ?, po_number = ?, date_in = ?, date_out = ?, signature = ?, updated_at = ?, created_at = ?, created_by = ?" + 
                    " WHERE order_id = " + getOrderId();
            try {
                ps = getConnection().prepareStatement(stmt);
                ps.setObject(1, getLocation());
                ps.setObject(2, getContractor());
                ps.setObject(3, getCustomerId());
                ps.setObject(4, getContactId());
                ps.setObject(5, getRigTankEq());
                ps.setObject(6, getDiscount());
                ps.setObject(7, getTaxProc());
                ps.setObject(8, getTaxId());
                ps.setObject(9, getPoTypeId());
                ps.setObject(10, getPoNumber());
                ps.setObject(11, getDateIn());
                ps.setObject(12, getDateOut());
                ps.setObject(13, getSignature());
                ps.setObject(14, getUpdatedAt());
                ps.setObject(15, getCreatedAt());
                ps.setObject(16, getCreatedBy());
                ps.execute();
            } finally {
                if (ps != null) ps.close();
            }
            setWasChanged(false);
            if (getTriggers() != null) {
                getTriggers().afterUpdate(this);
            }
        }
    }

    public void delete() throws SQLException, ForeignKeyViolationException {
        if (Orderitem.exists(getConnection(),"order_id = " + getOrderId())) {
            throw new ForeignKeyViolationException("Can't delete, foreign key violation: orderitem_order_fk");
        }
        if (getTriggers() != null) {
            getTriggers().beforeDelete(this);
        }
        PreparedStatement ps = null;
        String stmt =
                "DELETE FROM `order` " +
                "WHERE order_id = " + getOrderId();
        try {
            ps = getConnection().prepareStatement(stmt);
            ps.execute();
        } finally {
            if (ps != null) ps.close();
        }
        setOrderId(new Integer(-getOrderId().intValue()));
        if (getTriggers() != null) {
            getTriggers().afterDelete(this);
        }
    }

    public boolean isDeleted() {
        return (getOrderId().intValue() < 0);
    }

    public static DbObject[] load(Connection con,String whereCondition,String orderCondition) throws SQLException {
        ArrayList lst = new ArrayList();
        PreparedStatement ps = null;
        ResultSet rs = null;
        String stmt = "SELECT order_id,location,contractor,customer_id,contact_id,rig_tank_eq,discount,tax_proc,tax_id,po_type_id,po_number,date_in,date_out,signature,updated_at,created_at,created_by FROM `order` " +
                ((whereCondition != null && whereCondition.length() > 0) ?
                " WHERE " + whereCondition : "") +
                ((orderCondition != null && orderCondition.length() > 0) ?
                " ORDER BY " + orderCondition : "");
        try {
            ps = con.prepareStatement(stmt);
            rs = ps.executeQuery();
            while (rs.next()) {
                DbObject dbObj;
                lst.add(dbObj=new Order(con,new Integer(rs.getInt(1)),rs.getString(2),rs.getString(3),new Integer(rs.getInt(4)),new Integer(rs.getInt(5)),rs.getString(6),rs.getDouble(7),rs.getDouble(8),new Integer(rs.getInt(9)),new Integer(rs.getInt(10)),rs.getString(11),rs.getDate(12),rs.getDate(13),rs.getObject(14),rs.getTimestamp(15),rs.getTimestamp(16),new Integer(rs.getInt(17))));
                dbObj.setNew(false);
            }
        } finally {
            try {
                if (rs != null) rs.close();
            } finally {
                if (ps != null) ps.close();
            }
        }
        Order[] objects = new Order[lst.size()];
        for (int i = 0; i < lst.size(); i++) {
            Order order = (Order) lst.get(i);
            objects[i] = order;
        }
        return objects;
    }

    public static boolean exists(Connection con, String whereCondition) throws SQLException {
        if (con == null) {
            return true;
        }
        boolean ok = false;
        PreparedStatement ps = null;
        ResultSet rs = null;
        String stmt = "SELECT order_id FROM `order` " +
                ((whereCondition != null && whereCondition.length() > 0) ?
                "WHERE " + whereCondition : "");
        try {
            ps = con.prepareStatement(stmt);
            rs = ps.executeQuery();
            ok = rs.next();
        } finally {
            try {
                if (rs != null) rs.close();
            } finally {
                if (ps != null) ps.close();
            }
        }
        return ok;
    }

    //public String toString() {
    //    return getOrderId() + getDelimiter();
    //}

    public Integer getPK_ID() {
        return orderId;
    }

    public void setPK_ID(Integer id) throws ForeignKeyViolationException {
        boolean prevIsNew = isNew();
        setOrderId(id);
        setNew(prevIsNew);
    }

    public Integer getOrderId() {
        return orderId;
    }

    public void setOrderId(Integer orderId) throws ForeignKeyViolationException {
        setWasChanged(this.orderId != null && this.orderId != orderId);
        this.orderId = orderId;
        setNew(orderId.intValue() == 0);
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.location != null && !this.location.equals(location));
        this.location = location;
    }

    public String getContractor() {
        return contractor;
    }

    public void setContractor(String contractor) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.contractor != null && !this.contractor.equals(contractor));
        this.contractor = contractor;
    }

    public Integer getCustomerId() {
        return customerId;
    }

    public void setCustomerId(Integer customerId) throws SQLException, ForeignKeyViolationException {
        if (null != customerId)
            customerId = customerId == 0 ? null : customerId;
        if (customerId!=null && !Customer.exists(getConnection(),"customer_id = " + customerId)) {
            throw new ForeignKeyViolationException("Can't set customer_id, foreign key violation: order_customer_fk");
        }
        setWasChanged(this.customerId != null && !this.customerId.equals(customerId));
        this.customerId = customerId;
    }

    public Integer getContactId() {
        return contactId;
    }

    public void setContactId(Integer contactId) throws SQLException, ForeignKeyViolationException {
        if (null != contactId)
            contactId = contactId == 0 ? null : contactId;
        if (contactId!=null && !Contact.exists(getConnection(),"contact_id = " + contactId)) {
            throw new ForeignKeyViolationException("Can't set contact_id, foreign key violation: order_contact_fk");
        }
        setWasChanged(this.contactId != null && !this.contactId.equals(contactId));
        this.contactId = contactId;
    }

    public String getRigTankEq() {
        return rigTankEq;
    }

    public void setRigTankEq(String rigTankEq) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.rigTankEq != null && !this.rigTankEq.equals(rigTankEq));
        this.rigTankEq = rigTankEq;
    }

    public Double getDiscount() {
        return discount;
    }

    public void setDiscount(Double discount) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.discount != null && !this.discount.equals(discount));
        this.discount = discount;
    }

    public Double getTaxProc() {
        return taxProc;
    }

    public void setTaxProc(Double taxProc) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.taxProc != null && !this.taxProc.equals(taxProc));
        this.taxProc = taxProc;
    }

    public Integer getTaxId() {
        return taxId;
    }

    public void setTaxId(Integer taxId) throws SQLException, ForeignKeyViolationException {
        if (taxId!=null && !Tax.exists(getConnection(),"tax_id = " + taxId)) {
            throw new ForeignKeyViolationException("Can't set tax_id, foreign key violation: order_tax_fk");
        }
        setWasChanged(this.taxId != null && !this.taxId.equals(taxId));
        this.taxId = taxId;
    }

    public Integer getPoTypeId() {
        return poTypeId;
    }

    public void setPoTypeId(Integer poTypeId) throws SQLException, ForeignKeyViolationException {
        if (null != poTypeId)
            poTypeId = poTypeId == 0 ? null : poTypeId;
        if (poTypeId!=null && !Po.exists(getConnection(),"po_id = " + poTypeId)) {
            throw new ForeignKeyViolationException("Can't set po_type_id, foreign key violation: order_po_fk");
        }
        setWasChanged(this.poTypeId != null && !this.poTypeId.equals(poTypeId));
        this.poTypeId = poTypeId;
    }

    public String getPoNumber() {
        return poNumber;
    }

    public void setPoNumber(String poNumber) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.poNumber != null && !this.poNumber.equals(poNumber));
        this.poNumber = poNumber;
    }

    public Date getDateIn() {
        return dateIn;
    }

    public void setDateIn(Date dateIn) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.dateIn != null && !this.dateIn.equals(dateIn));
        this.dateIn = dateIn;
    }

    public Date getDateOut() {
        return dateOut;
    }

    public void setDateOut(Date dateOut) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.dateOut != null && !this.dateOut.equals(dateOut));
        this.dateOut = dateOut;
    }

    public Object getSignature() {
        return signature;
    }

    public void setSignature(Object signature) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.signature != null && !this.signature.equals(signature));
        this.signature = signature;
    }

    public Timestamp getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(Timestamp updatedAt) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.updatedAt != null && !this.updatedAt.equals(updatedAt));
        this.updatedAt = updatedAt;
    }

    public Timestamp getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Timestamp createdAt) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.createdAt != null && !this.createdAt.equals(createdAt));
        this.createdAt = createdAt;
    }

    public Integer getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(Integer createdBy) throws SQLException, ForeignKeyViolationException {
        if (createdBy!=null && !User.exists(getConnection(),"user_id = " + createdBy)) {
            throw new ForeignKeyViolationException("Can't set created_by, foreign key violation: order_user_fk");
        }
        setWasChanged(this.createdBy != null && !this.createdBy.equals(createdBy));
        this.createdBy = createdBy;
    }
    public Object[] getAsRow() {
        Object[] columnValues = new Object[17];
        columnValues[0] = getOrderId();
        columnValues[1] = getLocation();
        columnValues[2] = getContractor();
        columnValues[3] = getCustomerId();
        columnValues[4] = getContactId();
        columnValues[5] = getRigTankEq();
        columnValues[6] = getDiscount();
        columnValues[7] = getTaxProc();
        columnValues[8] = getTaxId();
        columnValues[9] = getPoTypeId();
        columnValues[10] = getPoNumber();
        columnValues[11] = getDateIn();
        columnValues[12] = getDateOut();
        columnValues[13] = getSignature();
        columnValues[14] = getUpdatedAt();
        columnValues[15] = getCreatedAt();
        columnValues[16] = getCreatedBy();
        return columnValues;
    }

    public static void setTriggers(Triggers triggers) {
        activeTriggers = triggers;
    }

    public static Triggers getTriggers() {
        return activeTriggers;
    }

    //for SOAP exhange
    @Override
    public void fillFromString(String row) throws ForeignKeyViolationException, SQLException {
        String[] flds = splitStr(row, delimiter);
        try {
            setOrderId(Integer.parseInt(flds[0]));
        } catch(NumberFormatException ne) {
            setOrderId(null);
        }
        setLocation(flds[1]);
        setContractor(flds[2]);
        try {
            setCustomerId(Integer.parseInt(flds[3]));
        } catch(NumberFormatException ne) {
            setCustomerId(null);
        }
        try {
            setContactId(Integer.parseInt(flds[4]));
        } catch(NumberFormatException ne) {
            setContactId(null);
        }
        setRigTankEq(flds[5]);
        try {
            setDiscount(Double.parseDouble(flds[6]));
        } catch(NumberFormatException ne) {
            setDiscount(null);
        }
        try {
            setTaxProc(Double.parseDouble(flds[7]));
        } catch(NumberFormatException ne) {
            setTaxProc(null);
        }
        try {
            setTaxId(Integer.parseInt(flds[8]));
        } catch(NumberFormatException ne) {
            setTaxId(null);
        }
        try {
            setPoTypeId(Integer.parseInt(flds[9]));
        } catch(NumberFormatException ne) {
            setPoTypeId(null);
        }
        setPoNumber(flds[10]);
        setDateIn(toDate(flds[11]));
        setDateOut(toDate(flds[12]));
        setSignature(flds[13]);
        setUpdatedAt(toTimeStamp(flds[14]));
        setCreatedAt(toTimeStamp(flds[15]));
        try {
            setCreatedBy(Integer.parseInt(flds[16]));
        } catch(NumberFormatException ne) {
            setCreatedBy(null);
        }
    }
}
