// Generated by com.xlend.orm.tools.dbgen.DbGenerator.class at Thu Nov 27 11:32:33 EET 2014
// generated file: do not modify
package com.as.orm;

import com.as.orm.dbobject.DbObject;
import com.as.orm.dbobject.ForeignKeyViolationException;
import com.as.orm.dbobject.Triggers;
import java.sql.*;
import java.util.ArrayList;

public class Order extends DbObject implements IDocument {
    private static Triggers activeTriggers = null;
    private Integer orderId = null;
    private String location = null;
    private String contractor = null;
    private String rigTankEq = null;
    private Double discount = null;
    private Double taxProc = null;
    private String poNumber = null;
    private Date dateIn = null;
    private Date dateOut = null;
    private Object signature = null;
    private Timestamp updatedAt = null;
    private Timestamp createdAt = null;
    private Integer createdBy = null;
    private Integer poTypeId = null;
    private Integer contactId = null;
    private Integer customerId = null;
    private Integer taxId = null;
    private Integer stampsId = null;
    private Double subtotal = null;
    private String wellName = null;
    private String afeUww = null;
    private String cai = null;
    private String aprvrName = null;
    private String dateStr = null;

    public Order(Connection connection) {
        super(connection, "order", "order_id");
        setColumnNames(new String[]{"order_id", "location", "contractor", "rig_tank_eq", "discount", "tax_proc", "po_number", "date_in", "date_out", "signature", "updated_at", "created_at", "created_by", "po_type_id", "contact_id", "customer_id", "tax_id", "stamps_id", "subtotal", "well_name", "afe_uww", "cai", "aprvr_name", "date_str"});
    }

    public Order(Connection connection, Integer orderId, String location, String contractor, String rigTankEq, Double discount, Double taxProc, String poNumber, Date dateIn, Date dateOut, Object signature, Timestamp updatedAt, Timestamp createdAt, Integer createdBy, Integer poTypeId, Integer contactId, Integer customerId, Integer taxId, Integer stampsId, Double subtotal, String wellName, String afeUww, String cai, String aprvrName, String dateStr) {
        super(connection, "order", "order_id");
        setNew(orderId.intValue() <= 0);
//        if (orderId.intValue() != 0) {
            this.orderId = orderId;
//        }
        this.location = location;
        this.contractor = contractor;
        this.rigTankEq = rigTankEq;
        this.discount = discount;
        this.taxProc = taxProc;
        this.poNumber = poNumber;
        this.dateIn = dateIn;
        this.dateOut = dateOut;
        this.signature = signature;
        this.updatedAt = updatedAt;
        this.createdAt = createdAt;
        this.createdBy = createdBy;
        this.poTypeId = poTypeId;
        this.contactId = contactId;
        this.customerId = customerId;
        this.taxId = taxId;
        this.stampsId = stampsId;
        this.subtotal = subtotal;
        this.wellName = wellName;
        this.afeUww = afeUww;
        this.cai = cai;
        this.aprvrName = aprvrName;
        this.dateStr = dateStr;
    }

    public DbObject loadOnId(int id) throws SQLException, ForeignKeyViolationException {
        Order order = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        String stmt = "SELECT order_id,location,contractor,rig_tank_eq,discount,tax_proc,po_number,date_in,date_out,signature,updated_at,created_at,created_by,po_type_id,contact_id,customer_id,tax_id,stamps_id,subtotal,well_name,afe_uww,cai,aprvr_name,date_str FROM `order` WHERE order_id=" + id;
        try {
            ps = getConnection().prepareStatement(stmt);
            rs = ps.executeQuery();
            if (rs.next()) {
                order = new Order(getConnection());
                order.setOrderId(new Integer(rs.getInt(1)));
                order.setLocation(rs.getString(2));
                order.setContractor(rs.getString(3));
                order.setRigTankEq(rs.getString(4));
                order.setDiscount(rs.getDouble(5));
                order.setTaxProc(rs.getDouble(6));
                order.setPoNumber(rs.getString(7));
                order.setDateIn(rs.getDate(8));
                order.setDateOut(rs.getDate(9));
                order.setSignature(rs.getObject(10));
                order.setUpdatedAt(rs.getTimestamp(11));
                order.setCreatedAt(rs.getTimestamp(12));
                order.setCreatedBy(new Integer(rs.getInt(13)));
                order.setPoTypeId(new Integer(rs.getInt(14)));
                order.setContactId(new Integer(rs.getInt(15)));
                order.setCustomerId(new Integer(rs.getInt(16)));
                order.setTaxId(new Integer(rs.getInt(17)));
                order.setStampsId(new Integer(rs.getInt(18)));
                order.setSubtotal(rs.getDouble(19));
                order.setWellName(rs.getString(20));
                order.setAfeUww(rs.getString(21));
                order.setCai(rs.getString(22));
                order.setAprvrName(rs.getString(23));
                order.setDateStr(rs.getString(24));
                order.setNew(false);
            }
        } finally {
            try {
                if (rs != null) rs.close();
            } finally {
                if (ps != null) ps.close();
            }
        }
        return order;
    }

    protected void insert() throws SQLException, ForeignKeyViolationException {
         if (getTriggers() != null) {
             getTriggers().beforeInsert(this);
         }
         PreparedStatement ps = null;
         String stmt =
                "INSERT INTO `order` ("+(getOrderId().intValue()!=0?"order_id,":"")+"location,contractor,rig_tank_eq,discount,tax_proc,po_number,date_in,date_out,signature,updated_at,created_at,created_by,po_type_id,contact_id,customer_id,tax_id,stamps_id,subtotal,well_name,afe_uww,cai,aprvr_name,date_str) values("+(getOrderId().intValue()!=0?"?,":"")+"?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
         try {
             ps = getConnection().prepareStatement(stmt);
             int n = 0;
             if (getOrderId().intValue()!=0) {
                 ps.setObject(++n, getOrderId());
             }
             ps.setObject(++n, getLocation());
             ps.setObject(++n, getContractor());
             ps.setObject(++n, getRigTankEq());
             ps.setObject(++n, getDiscount());
             ps.setObject(++n, getTaxProc());
             ps.setObject(++n, getPoNumber());
             ps.setObject(++n, getDateIn());
             ps.setObject(++n, getDateOut());
             ps.setObject(++n, getSignature());
             ps.setObject(++n, getUpdatedAt());
             ps.setObject(++n, getCreatedAt());
             ps.setObject(++n, getCreatedBy());
             ps.setObject(++n, getPoTypeId());
             ps.setObject(++n, getContactId());
             ps.setObject(++n, getCustomerId());
             ps.setObject(++n, getTaxId());
             ps.setObject(++n, getStampsId());
             ps.setObject(++n, getSubtotal());
             ps.setObject(++n, getWellName());
             ps.setObject(++n, getAfeUww());
             ps.setObject(++n, getCai());
             ps.setObject(++n, getAprvrName());
             ps.setObject(++n, getDateStr());
             ps.execute();
         } finally {
             if (ps != null) ps.close();
         }
         ResultSet rs = null;
         if (getOrderId().intValue()==0) {
             stmt = "SELECT max(order_id) FROM `order`";
             try {
                 ps = getConnection().prepareStatement(stmt);
                 rs = ps.executeQuery();
                 if (rs.next()) {
                     setOrderId(new Integer(rs.getInt(1)));
                 }
             } finally {
                 try {
                     if (rs != null) rs.close();
                 } finally {
                     if (ps != null) ps.close();
                 }
             }
         }
         setNew(false);
         setWasChanged(false);
         if (getTriggers() != null) {
             getTriggers().afterInsert(this);
         }
    }

    public void save() throws SQLException, ForeignKeyViolationException {
        if (isNew()) {
            insert();
        } else {
            if (getTriggers() != null) {
                getTriggers().beforeUpdate(this);
            }
            PreparedStatement ps = null;
            String stmt =
                    "UPDATE `order` " +
                    "SET location = ?, contractor = ?, rig_tank_eq = ?, discount = ?, tax_proc = ?, po_number = ?, date_in = ?, date_out = ?, signature = ?, updated_at = ?, created_at = ?, created_by = ?, po_type_id = ?, contact_id = ?, customer_id = ?, tax_id = ?, stamps_id = ?, subtotal = ?, well_name = ?, afe_uww = ?, cai = ?, aprvr_name = ?, date_str = ?" + 
                    " WHERE order_id = " + getOrderId();
            try {
                ps = getConnection().prepareStatement(stmt);
                ps.setObject(1, getLocation());
                ps.setObject(2, getContractor());
                ps.setObject(3, getRigTankEq());
                ps.setObject(4, getDiscount());
                ps.setObject(5, getTaxProc());
                ps.setObject(6, getPoNumber());
                ps.setObject(7, getDateIn());
                ps.setObject(8, getDateOut());
                ps.setObject(9, getSignature());
                ps.setObject(10, getUpdatedAt());
                ps.setObject(11, getCreatedAt());
                ps.setObject(12, getCreatedBy());
                ps.setObject(13, getPoTypeId());
                ps.setObject(14, getContactId());
                ps.setObject(15, getCustomerId());
                ps.setObject(16, getTaxId());
                ps.setObject(17, getStampsId());
                ps.setObject(18, getSubtotal());
                ps.setObject(19, getWellName());
                ps.setObject(20, getAfeUww());
                ps.setObject(21, getCai());
                ps.setObject(22, getAprvrName());
                ps.setObject(23, getDateStr());
                ps.execute();
            } finally {
                if (ps != null) ps.close();
            }
            setWasChanged(false);
            if (getTriggers() != null) {
                getTriggers().afterUpdate(this);
            }
        }
    }

    public void delete() throws SQLException, ForeignKeyViolationException {
        if (getTriggers() != null) {
            getTriggers().beforeDelete(this);
        }
        {// delete cascade from `order`item
            Orderitem[] records = (Orderitem[])Orderitem.load(getConnection(),"order_id = " + getOrderId(),null);
            for (int i = 0; i<records.length; i++) {
                Orderitem orderitem = records[i];
                orderitem.delete();
            }
        }
        PreparedStatement ps = null;
        String stmt =
                "DELETE FROM `order` " +
                "WHERE order_id = " + getOrderId();
        try {
            ps = getConnection().prepareStatement(stmt);
            ps.execute();
        } finally {
            if (ps != null) ps.close();
        }
        setOrderId(new Integer(-getOrderId().intValue()));
        if (getTriggers() != null) {
            getTriggers().afterDelete(this);
        }
    }

    public boolean isDeleted() {
        return (getOrderId().intValue() < 0);
    }

    public static DbObject[] load(Connection con,String whereCondition,String orderCondition) throws SQLException {
        ArrayList lst = new ArrayList();
        PreparedStatement ps = null;
        ResultSet rs = null;
        String stmt = "SELECT order_id,location,contractor,rig_tank_eq,discount,tax_proc,po_number,date_in,date_out,signature,updated_at,created_at,created_by,po_type_id,contact_id,customer_id,tax_id,stamps_id,subtotal,well_name,afe_uww,cai,aprvr_name,date_str FROM `order` " +
                ((whereCondition != null && whereCondition.length() > 0) ?
                " WHERE " + whereCondition : "") +
                ((orderCondition != null && orderCondition.length() > 0) ?
                " ORDER BY " + orderCondition : "");
        try {
            ps = con.prepareStatement(stmt);
            rs = ps.executeQuery();
            while (rs.next()) {
                DbObject dbObj;
                lst.add(dbObj=new Order(con,new Integer(rs.getInt(1)),rs.getString(2),rs.getString(3),rs.getString(4),rs.getDouble(5),rs.getDouble(6),rs.getString(7),rs.getDate(8),rs.getDate(9),rs.getObject(10),rs.getTimestamp(11),rs.getTimestamp(12),new Integer(rs.getInt(13)),new Integer(rs.getInt(14)),new Integer(rs.getInt(15)),new Integer(rs.getInt(16)),new Integer(rs.getInt(17)),new Integer(rs.getInt(18)),rs.getDouble(19),rs.getString(20),rs.getString(21),rs.getString(22),rs.getString(23),rs.getString(24)));
                dbObj.setNew(false);
            }
        } finally {
            try {
                if (rs != null) rs.close();
            } finally {
                if (ps != null) ps.close();
            }
        }
        Order[] objects = new Order[lst.size()];
        for (int i = 0; i < lst.size(); i++) {
            Order order = (Order) lst.get(i);
            objects[i] = order;
        }
        return objects;
    }

    public static boolean exists(Connection con, String whereCondition) throws SQLException {
        if (con == null) {
            return true;
        }
        boolean ok = false;
        PreparedStatement ps = null;
        ResultSet rs = null;
        String stmt = "SELECT order_id FROM `order` " +
                ((whereCondition != null && whereCondition.length() > 0) ?
                "WHERE " + whereCondition : "");
        try {
            ps = con.prepareStatement(stmt);
            rs = ps.executeQuery();
            ok = rs.next();
        } finally {
            try {
                if (rs != null) rs.close();
            } finally {
                if (ps != null) ps.close();
            }
        }
        return ok;
    }

    //public String toString() {
    //    return getOrderId() + getDelimiter();
    //}

    public Integer getPK_ID() {
        return orderId;
    }

    public void setPK_ID(Integer id) throws ForeignKeyViolationException {
        boolean prevIsNew = isNew();
        setOrderId(id);
        setNew(prevIsNew);
    }

    public Integer getOrderId() {
        return orderId;
    }

    public void setOrderId(Integer orderId) throws ForeignKeyViolationException {
        setWasChanged(this.orderId != null && this.orderId != orderId);
        this.orderId = orderId;
        setNew(orderId.intValue() == 0);
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.location != null && !this.location.equals(location));
        this.location = location;
    }

    public String getContractor() {
        return contractor;
    }

    public void setContractor(String contractor) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.contractor != null && !this.contractor.equals(contractor));
        this.contractor = contractor;
    }

    public String getRigTankEq() {
        return rigTankEq;
    }

    public void setRigTankEq(String rigTankEq) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.rigTankEq != null && !this.rigTankEq.equals(rigTankEq));
        this.rigTankEq = rigTankEq;
    }

    public Double getDiscount() {
        return discount;
    }

    public void setDiscount(Double discount) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.discount != null && !this.discount.equals(discount));
        this.discount = discount;
    }

    public Double getTaxProc() {
        return taxProc;
    }

    public void setTaxProc(Double taxProc) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.taxProc != null && !this.taxProc.equals(taxProc));
        this.taxProc = taxProc;
    }

    public String getPoNumber() {
        return poNumber;
    }

    public void setPoNumber(String poNumber) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.poNumber != null && !this.poNumber.equals(poNumber));
        this.poNumber = poNumber;
    }

    public Date getDateIn() {
        return dateIn;
    }

    public void setDateIn(Date dateIn) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.dateIn != null && !this.dateIn.equals(dateIn));
        this.dateIn = dateIn;
    }

    public Date getDateOut() {
        return dateOut;
    }

    public void setDateOut(Date dateOut) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.dateOut != null && !this.dateOut.equals(dateOut));
        this.dateOut = dateOut;
    }

    public Object getSignature() {
        return signature;
    }

    public void setSignature(Object signature) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.signature != null && !this.signature.equals(signature));
        this.signature = signature;
    }

    public Timestamp getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(Timestamp updatedAt) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.updatedAt != null && !this.updatedAt.equals(updatedAt));
        this.updatedAt = updatedAt;
    }

    public Timestamp getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Timestamp createdAt) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.createdAt != null && !this.createdAt.equals(createdAt));
        this.createdAt = createdAt;
    }

    public Integer getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(Integer createdBy) throws SQLException, ForeignKeyViolationException {
        if (createdBy!=null && !User.exists(getConnection(),"user_id = " + createdBy)) {
            throw new ForeignKeyViolationException("Can't set created_by, foreign key violation: order_user_fk");
        }
        setWasChanged(this.createdBy != null && !this.createdBy.equals(createdBy));
        this.createdBy = createdBy;
    }

    public Integer getPoTypeId() {
        return poTypeId;
    }

    public void setPoTypeId(Integer poTypeId) throws SQLException, ForeignKeyViolationException {
        if (null != poTypeId)
            poTypeId = poTypeId == 0 ? null : poTypeId;
        if (poTypeId!=null && !Po.exists(getConnection(),"po_id = " + poTypeId)) {
            throw new ForeignKeyViolationException("Can't set po_type_id, foreign key violation: order_po_fk");
        }
        setWasChanged(this.poTypeId != null && !this.poTypeId.equals(poTypeId));
        this.poTypeId = poTypeId;
    }

    public Integer getContactId() {
        return contactId;
    }

    public void setContactId(Integer contactId) throws SQLException, ForeignKeyViolationException {
        if (null != contactId)
            contactId = contactId == 0 ? null : contactId;
        if (contactId!=null && !Contact.exists(getConnection(),"contact_id = " + contactId)) {
            throw new ForeignKeyViolationException("Can't set contact_id, foreign key violation: order_contact_fk");
        }
        setWasChanged(this.contactId != null && !this.contactId.equals(contactId));
        this.contactId = contactId;
    }

    public Integer getCustomerId() {
        return customerId;
    }

    public void setCustomerId(Integer customerId) throws SQLException, ForeignKeyViolationException {
        if (null != customerId)
            customerId = customerId == 0 ? null : customerId;
        if (customerId!=null && !Customer.exists(getConnection(),"customer_id = " + customerId)) {
            throw new ForeignKeyViolationException("Can't set customer_id, foreign key violation: order_customer_fk");
        }
        setWasChanged(this.customerId != null && !this.customerId.equals(customerId));
        this.customerId = customerId;
    }

    public Integer getTaxId() {
        return taxId;
    }

    public void setTaxId(Integer taxId) throws SQLException, ForeignKeyViolationException {
        if (null != taxId)
            taxId = taxId == 0 ? null : taxId;
        if (taxId!=null && !Tax.exists(getConnection(),"tax_id = " + taxId)) {
            throw new ForeignKeyViolationException("Can't set tax_id, foreign key violation: order_tax_fk");
        }
        setWasChanged(this.taxId != null && !this.taxId.equals(taxId));
        this.taxId = taxId;
    }

    public Integer getStampsId() {
        return stampsId;
    }

    public void setStampsId(Integer stampsId) throws SQLException, ForeignKeyViolationException {
        if (null != stampsId)
            stampsId = stampsId == 0 ? null : stampsId;
        if (stampsId!=null && !Stamps.exists(getConnection(),"stamps_id = " + stampsId)) {
            throw new ForeignKeyViolationException("Can't set stamps_id, foreign key violation: order_stamps_fk");
        }
        setWasChanged(this.stampsId != null && !this.stampsId.equals(stampsId));
        this.stampsId = stampsId;
    }

    public Double getSubtotal() {
        return subtotal;
    }

    public void setSubtotal(Double subtotal) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.subtotal != null && !this.subtotal.equals(subtotal));
        this.subtotal = subtotal;
    }

    public String getWellName() {
        return wellName;
    }

    public void setWellName(String wellName) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.wellName != null && !this.wellName.equals(wellName));
        this.wellName = wellName;
    }

    public String getAfeUww() {
        return afeUww;
    }

    public void setAfeUww(String afeUww) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.afeUww != null && !this.afeUww.equals(afeUww));
        this.afeUww = afeUww;
    }

    public String getCai() {
        return cai;
    }

    public void setCai(String cai) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.cai != null && !this.cai.equals(cai));
        this.cai = cai;
    }

    public String getAprvrName() {
        return aprvrName;
    }

    public void setAprvrName(String aprvrName) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.aprvrName != null && !this.aprvrName.equals(aprvrName));
        this.aprvrName = aprvrName;
    }

    public String getDateStr() {
        return dateStr;
    }

    public void setDateStr(String dateStr) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.dateStr != null && !this.dateStr.equals(dateStr));
        this.dateStr = dateStr;
    }
    public Object[] getAsRow() {
        Object[] columnValues = new Object[24];
        columnValues[0] = getOrderId();
        columnValues[1] = getLocation();
        columnValues[2] = getContractor();
        columnValues[3] = getRigTankEq();
        columnValues[4] = getDiscount();
        columnValues[5] = getTaxProc();
        columnValues[6] = getPoNumber();
        columnValues[7] = getDateIn();
        columnValues[8] = getDateOut();
        columnValues[9] = getSignature();
        columnValues[10] = getUpdatedAt();
        columnValues[11] = getCreatedAt();
        columnValues[12] = getCreatedBy();
        columnValues[13] = getPoTypeId();
        columnValues[14] = getContactId();
        columnValues[15] = getCustomerId();
        columnValues[16] = getTaxId();
        columnValues[17] = getStampsId();
        columnValues[18] = getSubtotal();
        columnValues[19] = getWellName();
        columnValues[20] = getAfeUww();
        columnValues[21] = getCai();
        columnValues[22] = getAprvrName();
        columnValues[23] = getDateStr();
        return columnValues;
    }

    public static void setTriggers(Triggers triggers) {
        activeTriggers = triggers;
    }

    public static Triggers getTriggers() {
        return activeTriggers;
    }

    //for SOAP exhange
    @Override
    public void fillFromString(String row) throws ForeignKeyViolationException, SQLException {
        String[] flds = splitStr(row, delimiter);
        try {
            setOrderId(Integer.parseInt(flds[0]));
        } catch(NumberFormatException ne) {
            setOrderId(null);
        }
        setLocation(flds[1]);
        setContractor(flds[2]);
        setRigTankEq(flds[3]);
        try {
            setDiscount(Double.parseDouble(flds[4]));
        } catch(NumberFormatException ne) {
            setDiscount(null);
        }
        try {
            setTaxProc(Double.parseDouble(flds[5]));
        } catch(NumberFormatException ne) {
            setTaxProc(null);
        }
        setPoNumber(flds[6]);
        setDateIn(toDate(flds[7]));
        setDateOut(toDate(flds[8]));
        setSignature(flds[9]);
        setUpdatedAt(toTimeStamp(flds[10]));
        setCreatedAt(toTimeStamp(flds[11]));
        try {
            setCreatedBy(Integer.parseInt(flds[12]));
        } catch(NumberFormatException ne) {
            setCreatedBy(null);
        }
        try {
            setPoTypeId(Integer.parseInt(flds[13]));
        } catch(NumberFormatException ne) {
            setPoTypeId(null);
        }
        try {
            setContactId(Integer.parseInt(flds[14]));
        } catch(NumberFormatException ne) {
            setContactId(null);
        }
        try {
            setCustomerId(Integer.parseInt(flds[15]));
        } catch(NumberFormatException ne) {
            setCustomerId(null);
        }
        try {
            setTaxId(Integer.parseInt(flds[16]));
        } catch(NumberFormatException ne) {
            setTaxId(null);
        }
        try {
            setStampsId(Integer.parseInt(flds[17]));
        } catch(NumberFormatException ne) {
            setStampsId(null);
        }
        try {
            setSubtotal(Double.parseDouble(flds[18]));
        } catch(NumberFormatException ne) {
            setSubtotal(null);
        }
        setWellName(flds[19]);
        setAfeUww(flds[20]);
        setCai(flds[21]);
        setAprvrName(flds[22]);
        setDateStr(flds[23]);
    }
}
