// Generated by com.xlend.orm.tools.dbgen.DbGenerator.class at Thu Nov 27 11:32:33 EET 2014
// generated file: do not modify
package com.as.orm;

import com.as.orm.dbobject.DbObject;
import com.as.orm.dbobject.ForeignKeyViolationException;
import com.as.orm.dbobject.Triggers;
import java.sql.*;
import java.util.ArrayList;

public class Role extends DbObject  {
    private static Triggers activeTriggers = null;
    private Integer roleId = null;
    private String roleName = null;

    public Role(Connection connection) {
        super(connection, "role", "role_id");
        setColumnNames(new String[]{"role_id", "role_name"});
    }

    public Role(Connection connection, Integer roleId, String roleName) {
        super(connection, "role", "role_id");
        setNew(roleId.intValue() <= 0);
//        if (roleId.intValue() != 0) {
            this.roleId = roleId;
//        }
        this.roleName = roleName;
    }

    public DbObject loadOnId(int id) throws SQLException, ForeignKeyViolationException {
        Role role = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        String stmt = "SELECT role_id,role_name FROM role WHERE role_id=" + id;
        try {
            ps = getConnection().prepareStatement(stmt);
            rs = ps.executeQuery();
            if (rs.next()) {
                role = new Role(getConnection());
                role.setRoleId(new Integer(rs.getInt(1)));
                role.setRoleName(rs.getString(2));
                role.setNew(false);
            }
        } finally {
            try {
                if (rs != null) rs.close();
            } finally {
                if (ps != null) ps.close();
            }
        }
        return role;
    }

    protected void insert() throws SQLException, ForeignKeyViolationException {
         if (getTriggers() != null) {
             getTriggers().beforeInsert(this);
         }
         PreparedStatement ps = null;
         String stmt =
                "INSERT INTO role ("+(getRoleId().intValue()!=0?"role_id,":"")+"role_name) values("+(getRoleId().intValue()!=0?"?,":"")+"?)";
         try {
             ps = getConnection().prepareStatement(stmt);
             int n = 0;
             if (getRoleId().intValue()!=0) {
                 ps.setObject(++n, getRoleId());
             }
             ps.setObject(++n, getRoleName());
             ps.execute();
         } finally {
             if (ps != null) ps.close();
         }
         ResultSet rs = null;
         if (getRoleId().intValue()==0) {
             stmt = "SELECT max(role_id) FROM role";
             try {
                 ps = getConnection().prepareStatement(stmt);
                 rs = ps.executeQuery();
                 if (rs.next()) {
                     setRoleId(new Integer(rs.getInt(1)));
                 }
             } finally {
                 try {
                     if (rs != null) rs.close();
                 } finally {
                     if (ps != null) ps.close();
                 }
             }
         }
         setNew(false);
         setWasChanged(false);
         if (getTriggers() != null) {
             getTriggers().afterInsert(this);
         }
    }

    public void save() throws SQLException, ForeignKeyViolationException {
        if (isNew()) {
            insert();
        } else {
            if (getTriggers() != null) {
                getTriggers().beforeUpdate(this);
            }
            PreparedStatement ps = null;
            String stmt =
                    "UPDATE role " +
                    "SET role_name = ?" + 
                    " WHERE role_id = " + getRoleId();
            try {
                ps = getConnection().prepareStatement(stmt);
                ps.setObject(1, getRoleName());
                ps.execute();
            } finally {
                if (ps != null) ps.close();
            }
            setWasChanged(false);
            if (getTriggers() != null) {
                getTriggers().afterUpdate(this);
            }
        }
    }

    public void delete() throws SQLException, ForeignKeyViolationException {
        if (Usersrole.exists(getConnection(),"role_id = " + getRoleId())) {
            throw new ForeignKeyViolationException("Can't delete, foreign key violation: usersrole_role_fk");
        }
        if (getTriggers() != null) {
            getTriggers().beforeDelete(this);
        }
        PreparedStatement ps = null;
        String stmt =
                "DELETE FROM role " +
                "WHERE role_id = " + getRoleId();
        try {
            ps = getConnection().prepareStatement(stmt);
            ps.execute();
        } finally {
            if (ps != null) ps.close();
        }
        setRoleId(new Integer(-getRoleId().intValue()));
        if (getTriggers() != null) {
            getTriggers().afterDelete(this);
        }
    }

    public boolean isDeleted() {
        return (getRoleId().intValue() < 0);
    }

    public static DbObject[] load(Connection con,String whereCondition,String orderCondition) throws SQLException {
        ArrayList lst = new ArrayList();
        PreparedStatement ps = null;
        ResultSet rs = null;
        String stmt = "SELECT role_id,role_name FROM role " +
                ((whereCondition != null && whereCondition.length() > 0) ?
                " WHERE " + whereCondition : "") +
                ((orderCondition != null && orderCondition.length() > 0) ?
                " ORDER BY " + orderCondition : "");
        try {
            ps = con.prepareStatement(stmt);
            rs = ps.executeQuery();
            while (rs.next()) {
                DbObject dbObj;
                lst.add(dbObj=new Role(con,new Integer(rs.getInt(1)),rs.getString(2)));
                dbObj.setNew(false);
            }
        } finally {
            try {
                if (rs != null) rs.close();
            } finally {
                if (ps != null) ps.close();
            }
        }
        Role[] objects = new Role[lst.size()];
        for (int i = 0; i < lst.size(); i++) {
            Role role = (Role) lst.get(i);
            objects[i] = role;
        }
        return objects;
    }

    public static boolean exists(Connection con, String whereCondition) throws SQLException {
        if (con == null) {
            return true;
        }
        boolean ok = false;
        PreparedStatement ps = null;
        ResultSet rs = null;
        String stmt = "SELECT role_id FROM role " +
                ((whereCondition != null && whereCondition.length() > 0) ?
                "WHERE " + whereCondition : "");
        try {
            ps = con.prepareStatement(stmt);
            rs = ps.executeQuery();
            ok = rs.next();
        } finally {
            try {
                if (rs != null) rs.close();
            } finally {
                if (ps != null) ps.close();
            }
        }
        return ok;
    }

    //public String toString() {
    //    return getRoleId() + getDelimiter();
    //}

    public Integer getPK_ID() {
        return roleId;
    }

    public void setPK_ID(Integer id) throws ForeignKeyViolationException {
        boolean prevIsNew = isNew();
        setRoleId(id);
        setNew(prevIsNew);
    }

    public Integer getRoleId() {
        return roleId;
    }

    public void setRoleId(Integer roleId) throws ForeignKeyViolationException {
        setWasChanged(this.roleId != null && this.roleId != roleId);
        this.roleId = roleId;
        setNew(roleId.intValue() == 0);
    }

    public String getRoleName() {
        return roleName;
    }

    public void setRoleName(String roleName) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.roleName != null && !this.roleName.equals(roleName));
        this.roleName = roleName;
    }
    public Object[] getAsRow() {
        Object[] columnValues = new Object[2];
        columnValues[0] = getRoleId();
        columnValues[1] = getRoleName();
        return columnValues;
    }

    public static void setTriggers(Triggers triggers) {
        activeTriggers = triggers;
    }

    public static Triggers getTriggers() {
        return activeTriggers;
    }

    //for SOAP exhange
    @Override
    public void fillFromString(String row) throws ForeignKeyViolationException, SQLException {
        String[] flds = splitStr(row, delimiter);
        try {
            setRoleId(Integer.parseInt(flds[0]));
        } catch(NumberFormatException ne) {
            setRoleId(null);
        }
        setRoleName(flds[1]);
    }
}
