// Generated by com.xlend.orm.tools.dbgen.DbGenerator.class at Wed Oct 29 17:58:28 EET 2014
// generated file: do not modify
package com.as.orm;

import com.as.orm.dbobject.DbObject;
import com.as.orm.dbobject.ForeignKeyViolationException;
import com.as.orm.dbobject.Triggers;
import java.sql.*;
import java.util.ArrayList;

public class Tax extends DbObject  {
    private static Triggers activeTriggers = null;
    private Integer taxId = null;
    private String taxDescription = null;

    public Tax(Connection connection) {
        super(connection, "tax", "tax_id");
        setColumnNames(new String[]{"tax_id", "tax_description"});
    }

    public Tax(Connection connection, Integer taxId, String taxDescription) {
        super(connection, "tax", "tax_id");
        setNew(taxId.intValue() <= 0);
//        if (taxId.intValue() != 0) {
            this.taxId = taxId;
//        }
        this.taxDescription = taxDescription;
    }

    public DbObject loadOnId(int id) throws SQLException, ForeignKeyViolationException {
        Tax tax = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        String stmt = "SELECT tax_id,tax_description FROM tax WHERE tax_id=" + id;
        try {
            ps = getConnection().prepareStatement(stmt);
            rs = ps.executeQuery();
            if (rs.next()) {
                tax = new Tax(getConnection());
                tax.setTaxId(new Integer(rs.getInt(1)));
                tax.setTaxDescription(rs.getString(2));
                tax.setNew(false);
            }
        } finally {
            try {
                if (rs != null) rs.close();
            } finally {
                if (ps != null) ps.close();
            }
        }
        return tax;
    }

    protected void insert() throws SQLException, ForeignKeyViolationException {
         if (getTriggers() != null) {
             getTriggers().beforeInsert(this);
         }
         PreparedStatement ps = null;
         String stmt =
                "INSERT INTO tax ("+(getTaxId().intValue()!=0?"tax_id,":"")+"tax_description) values("+(getTaxId().intValue()!=0?"?,":"")+"?)";
         try {
             ps = getConnection().prepareStatement(stmt);
             int n = 0;
             if (getTaxId().intValue()!=0) {
                 ps.setObject(++n, getTaxId());
             }
             ps.setObject(++n, getTaxDescription());
             ps.execute();
         } finally {
             if (ps != null) ps.close();
         }
         ResultSet rs = null;
         if (getTaxId().intValue()==0) {
             stmt = "SELECT max(tax_id) FROM tax";
             try {
                 ps = getConnection().prepareStatement(stmt);
                 rs = ps.executeQuery();
                 if (rs.next()) {
                     setTaxId(new Integer(rs.getInt(1)));
                 }
             } finally {
                 try {
                     if (rs != null) rs.close();
                 } finally {
                     if (ps != null) ps.close();
                 }
             }
         }
         setNew(false);
         setWasChanged(false);
         if (getTriggers() != null) {
             getTriggers().afterInsert(this);
         }
    }

    public void save() throws SQLException, ForeignKeyViolationException {
        if (isNew()) {
            insert();
        } else {
            if (getTriggers() != null) {
                getTriggers().beforeUpdate(this);
            }
            PreparedStatement ps = null;
            String stmt =
                    "UPDATE tax " +
                    "SET tax_description = ?" + 
                    " WHERE tax_id = " + getTaxId();
            try {
                ps = getConnection().prepareStatement(stmt);
                ps.setObject(1, getTaxDescription());
                ps.execute();
            } finally {
                if (ps != null) ps.close();
            }
            setWasChanged(false);
            if (getTriggers() != null) {
                getTriggers().afterUpdate(this);
            }
        }
    }

    public void delete() throws SQLException, ForeignKeyViolationException {
        if (Invoice.exists(getConnection(),"tax_id = " + getTaxId())) {
            throw new ForeignKeyViolationException("Can't delete, foreign key violation: invoice_tax_fk");
        }
        if (Quote.exists(getConnection(),"tax_id = " + getTaxId())) {
            throw new ForeignKeyViolationException("Can't delete, foreign key violation: quote_tax_fk");
        }
        if (Order.exists(getConnection(),"tax_id = " + getTaxId())) {
            throw new ForeignKeyViolationException("Can't delete, foreign key violation: order_tax_fk");
        }
        if (getTriggers() != null) {
            getTriggers().beforeDelete(this);
        }
        PreparedStatement ps = null;
        String stmt =
                "DELETE FROM tax " +
                "WHERE tax_id = " + getTaxId();
        try {
            ps = getConnection().prepareStatement(stmt);
            ps.execute();
        } finally {
            if (ps != null) ps.close();
        }
        setTaxId(new Integer(-getTaxId().intValue()));
        if (getTriggers() != null) {
            getTriggers().afterDelete(this);
        }
    }

    public boolean isDeleted() {
        return (getTaxId().intValue() < 0);
    }

    public static DbObject[] load(Connection con,String whereCondition,String orderCondition) throws SQLException {
        ArrayList lst = new ArrayList();
        PreparedStatement ps = null;
        ResultSet rs = null;
        String stmt = "SELECT tax_id,tax_description FROM tax " +
                ((whereCondition != null && whereCondition.length() > 0) ?
                " WHERE " + whereCondition : "") +
                ((orderCondition != null && orderCondition.length() > 0) ?
                " ORDER BY " + orderCondition : "");
        try {
            ps = con.prepareStatement(stmt);
            rs = ps.executeQuery();
            while (rs.next()) {
                DbObject dbObj;
                lst.add(dbObj=new Tax(con,new Integer(rs.getInt(1)),rs.getString(2)));
                dbObj.setNew(false);
            }
        } finally {
            try {
                if (rs != null) rs.close();
            } finally {
                if (ps != null) ps.close();
            }
        }
        Tax[] objects = new Tax[lst.size()];
        for (int i = 0; i < lst.size(); i++) {
            Tax tax = (Tax) lst.get(i);
            objects[i] = tax;
        }
        return objects;
    }

    public static boolean exists(Connection con, String whereCondition) throws SQLException {
        if (con == null) {
            return true;
        }
        boolean ok = false;
        PreparedStatement ps = null;
        ResultSet rs = null;
        String stmt = "SELECT tax_id FROM tax " +
                ((whereCondition != null && whereCondition.length() > 0) ?
                "WHERE " + whereCondition : "");
        try {
            ps = con.prepareStatement(stmt);
            rs = ps.executeQuery();
            ok = rs.next();
        } finally {
            try {
                if (rs != null) rs.close();
            } finally {
                if (ps != null) ps.close();
            }
        }
        return ok;
    }

    //public String toString() {
    //    return getTaxId() + getDelimiter();
    //}

    public Integer getPK_ID() {
        return taxId;
    }

    public void setPK_ID(Integer id) throws ForeignKeyViolationException {
        boolean prevIsNew = isNew();
        setTaxId(id);
        setNew(prevIsNew);
    }

    public Integer getTaxId() {
        return taxId;
    }

    public void setTaxId(Integer taxId) throws ForeignKeyViolationException {
        setWasChanged(this.taxId != null && this.taxId != taxId);
        this.taxId = taxId;
        setNew(taxId.intValue() == 0);
    }

    public String getTaxDescription() {
        return taxDescription;
    }

    public void setTaxDescription(String taxDescription) throws SQLException, ForeignKeyViolationException {
        setWasChanged(this.taxDescription != null && !this.taxDescription.equals(taxDescription));
        this.taxDescription = taxDescription;
    }
    public Object[] getAsRow() {
        Object[] columnValues = new Object[2];
        columnValues[0] = getTaxId();
        columnValues[1] = getTaxDescription();
        return columnValues;
    }

    public static void setTriggers(Triggers triggers) {
        activeTriggers = triggers;
    }

    public static Triggers getTriggers() {
        return activeTriggers;
    }

    //for SOAP exhange
    @Override
    public void fillFromString(String row) throws ForeignKeyViolationException, SQLException {
        String[] flds = splitStr(row, delimiter);
        try {
            setTaxId(Integer.parseInt(flds[0]));
        } catch(NumberFormatException ne) {
            setTaxId(null);
        }
        setTaxDescription(flds[1]);
    }
}
